#!/bin/bash

function destroy {
  vagrant destroy -f $1 &
}

destroy item-read-front
destroy item-read-back
#destroy item-write-front
#destroy item-write-back

while true; do
	if docker ps | grep -e "item\|ecommerce-view-store|ecommerce-eventstore"; then
		sleep 0.3
	else
		break
	fi
done

echo "System destroyed."